import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import {
  TrendingUp,
  TrendingDown,
  ChevronDown,
  PiggyBank,
  Calendar,
  Briefcase,
} from "lucide-react";
import { useTheme } from "../contexts/ThemeContext";
import { useLanguage } from "../contexts/LanguageContext";
import profileImage from "../assets/man_pfp.png";

const sidebarCopy = {
  en: {
    profileTitle: "My Profile",
    moreInfo: "More info",
    income: "Income",
    expenses: "Expenses",
    netSavings: "Net savings",
    monthlySalary: "Monthly salary",
    seniority: "Seniority",
    perFebruary: "For February",
    perMonth: "Per month",
    years: "years",
    recommendationsTitle: "Personalized recommendations",
    recommendationsBody:
      "Banking product suggestions adapted to your profile among 7 classes and 38 BH Bank products, generated by an analysis engine combining behavioral segmentation and business rules.",
    questionTitle: "Do you have a question?",
    questionSubtitle: "Would you like to know your credit eligibility?",
    askUs: "Ask us",
  },
  fr: {
    profileTitle: "Mon Profil",
    moreInfo: "Plus d'infos",
    income: "Revenus",
    expenses: "Depenses",
    netSavings: "Epargne nette",
    monthlySalary: "Salaire mensuel",
    seniority: "Anciennete",
    perFebruary: "Par fevrier",
    perMonth: "Par mois",
    years: "ans",
    recommendationsTitle: "Recommandations personnalisees",
    recommendationsBody:
      "Suggestions de produits bancaires adaptes a votre profil parmi 7 classes et 38 produits BH Bank, generees par un moteur d'analyse combinant segmentation comportementale et regles metier.",
    questionTitle: "Vous avez une question ?",
    questionSubtitle: "Voulez-vous connaitre votre eligibilite au credit ?",
    askUs: "Demandez-nous",
  },
  ar: {
    profileTitle: "ملفي الشخصي",
    moreInfo: "مزيد من المعلومات",
    income: "الدخل",
    expenses: "المصاريف",
    netSavings: "الادخار الصافي",
    monthlySalary: "الراتب الشهري",
    seniority: "الاقدمية",
    perFebruary: "لشهر فيفري",
    perMonth: "شهريا",
    years: "سنوات",
    recommendationsTitle: "توصيات مخصصة",
    recommendationsBody:
      "اقتراحات لمنتجات بنكية مناسبة لملفك ضمن 7 اصناف و38 منتجا من BH Bank، يتم توليدها عبر محرك تحليل يجمع بين التقسيم السلوكي وقواعد الاعمال.",
    questionTitle: "هل لديك سؤال؟",
    questionSubtitle: "هل تريد معرفة اهليتك للحصول على قرض؟",
    askUs: "اسالنا",
  },
};

export function ProfileSidebar({ isVisible }) {
  const navigate = useNavigate();
  const { theme } = useTheme();
  const { language, isRTL } = useLanguage();
  const [showRecommendations, setShowRecommendations] = useState(true);
  const isDark = theme === "dark";
  const ui = sidebarCopy[language] || sidebarCopy.en;

  const labelClass = isDark ? "text-gray-300" : "text-gray-500";
  const valueClass = isDark ? "text-white" : "text-gray-900";
  const metaClass = isDark ? "text-gray-400" : "text-gray-500";

  const statCards = [
    {
      key: "income",
      icon: TrendingUp,
      value: "1 448 TND",
      meta: ui.perFebruary,
      showChevron: true,
      cardClass: isDark
        ? "bg-emerald-900/20 border-emerald-800/40"
        : "bg-emerald-50 border-emerald-100",
      iconClass: "bg-emerald-600",
    },
    {
      key: "expenses",
      icon: TrendingDown,
      value: "2 075 TND",
      meta: ui.perFebruary,
      showChevron: true,
      cardClass: isDark
        ? "bg-rose-900/20 border-rose-800/40"
        : "bg-rose-50 border-rose-100",
      iconClass: "bg-rose-600",
    },
    {
      key: "netSavings",
      icon: PiggyBank,
      value: "627 TND",
      meta: ui.perMonth,
      showChevron: true,
      cardClass: isDark
        ? "bg-teal-900/20 border-teal-800/40"
        : "bg-teal-50 border-teal-100",
      iconClass: "bg-green-600",
    },
    {
      key: "monthlySalary",
      icon: Calendar,
      value: "3 500 TND",
      cardClass: isDark
        ? "bg-blue-900/20 border-blue-800/40"
        : "bg-blue-50 border-blue-100",
      iconClass: "bg-blue-600",
    },
    {
      key: "seniority",
      icon: Briefcase,
      value: `5 ${ui.years}`,
      cardClass: isDark
        ? "bg-purple-900/20 border-purple-800/40"
        : "bg-purple-50 border-purple-100",
      iconClass: "bg-purple-600",
    },
  ];

  useEffect(() => {
    if (!isVisible) return undefined;

    const showTimer = setTimeout(() => {
      setShowRecommendations(true);
    }, 0);

    const hideTimer = setTimeout(() => {
      setShowRecommendations(false);
    }, 4000);

    return () => {
      clearTimeout(showTimer);
      clearTimeout(hideTimer);
    };
  }, [isVisible]);

  if (!isVisible) return null;

  return (
    <div
      className={`w-80 border-l ${
        isDark ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
      } p-8 space-y-6 h-screen overflow-y-auto ${isRTL ? "text-right" : "text-left"}`}
    >
      <div className={isRTL ? "text-right" : "text-left"}>
        <h2
          className={`text-lg leading-tight font-medium ${
            isDark ? "text-white" : "text-gray-900"
          }`}
        >
          {ui.profileTitle}
        </h2>
      </div>

      <div className="flex flex-col items-center text-center space-y-3">
        <img
          src={profileImage}
          alt="Martin Bratik"
          className="w-24 h-24 rounded-full object-cover"
        />
        <div>
          <h3 className={`font-medium text-lg ${valueClass}`}>Martin Bratik</h3>
          <p className={`text-sm ${metaClass}`}>martin.bratik@gmail.com</p>
        </div>
        <button
          onClick={() => navigate("/profile")}
          className="text-sm text-blue-600 hover:text-blue-700"
        >
          {ui.moreInfo}
        </button>
      </div>

      <div className="space-y-3">
        {statCards.map((card) => {
          const Icon = card.icon;

          return (
            <div
              key={card.key}
              className={`flex items-center justify-between p-4 rounded-xl border ${card.cardClass}`}
            >
              <div className={`flex items-center gap-3 ${isRTL ? "flex-row-reverse" : ""}`}>
                <div
                  className={`w-10 h-10 ${card.iconClass} rounded-lg flex items-center justify-center shrink-0`}
                >
                  <Icon className="w-5 h-5 text-white" />
                </div>
                <div>
                  <p className={`text-xs ${labelClass}`}>{ui[card.key]}</p>
                  <p className={`text-lg font-semibold ${valueClass}`}>{card.value}</p>
                </div>
              </div>

              {card.meta && (
                <div className={`flex items-center gap-1 text-xs ${metaClass} ${isRTL ? "flex-row-reverse" : ""}`}>
                  <span>{card.meta}</span>
                  {card.showChevron && <ChevronDown className="w-4 h-4" />}
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div
        className={`rounded-xl p-5 border min-h-45 flex flex-col justify-center ${
          isDark
            ? "bg-linear-to-br from-[#13263f] to-[#1f3255] border-[#2a3f66]"
            : "bg-linear-to-br from-blue-50 to-purple-50 border-blue-100"
        } ${isRTL ? "text-right" : "text-left"}`}
      >
        {showRecommendations ? (
          <div className="space-y-3">
            <div className={`flex items-center gap-2 ${isRTL ? "flex-row-reverse" : ""}`}>
              <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shrink-0">
                <svg
                  className="w-5 h-5 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                  />
                </svg>
              </div>
              <h3
                className={`text-sm font-semibold ${
                  isDark ? "text-white" : "text-gray-800"
                }`}
              >
                {ui.recommendationsTitle}
              </h3>
            </div>
            <p
              className={`text-xs leading-relaxed ${
                isDark ? "text-gray-300" : "text-gray-600"
              }`}
            >
              {ui.recommendationsBody}
            </p>
          </div>
        ) : (
          <div className="space-y-4 text-center">
            <div className="space-y-2">
              <p className={`text-sm font-medium ${isDark ? "text-white" : "text-gray-800"}`}>
                {ui.questionTitle}
              </p>
              <p className={`text-sm ${isDark ? "text-gray-300" : "text-gray-600"}`}>
                {ui.questionSubtitle}
              </p>
            </div>
            <button
              onClick={() => navigate("/chatbot")}
              className="w-full px-4 py-3 bg-linear-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all shadow-md hover:shadow-lg font-medium"
            >
              {ui.askUs}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
